### ISSUE TITLE
Disallowed Mod CoNflict

### ISSUE THREAD

**Issue by Yahooligan2** [Byte-Nova/Rimworld-Together#27]
While logging in with an established account, I recieve the error: 

![image](https://github.com/Byte-Nova/Rimworld-Together/assets/163966007/2585d26e-b5b9-47ac-9559-2be6ff1a47ed)

All the mods in my required mod folder are properly installed.

Any guidance is appreciated!

Thanks

**Comment by Byte-Nova** [comment]
Hello, it appears you are missing the CORE files of the game, the server won't let you in since you are missing them inside the server allowed mods. You can download it from our repository, the file called "Extras.zip" contains everything you might need

![Capture](https://github.com/Byte-Nova/Rimworld-Together/assets/159603018/2a66f265-7263-42a9-a936-1e16fd789812)
